/// <summary>
/// 드랍아이템
/// </summary>
public enum ECurrenctType 
{
    Wood_Sword,
    Stone_Sword,
    Silver_Sword,
    Gold_Sword,
    Wood_Axe,
    Stone_Axe,
    puSilver_Axe ,
    Gold_Axe ,
    Wood_Fork ,
    Stone_Fork ,
    Silver_Fork ,
    Gold_Fork,
    Wood_Hammer ,
    Stone_Hammer ,
    Silver_Hammer,
    Gold_Hammer ,
    Wood_Spoon ,
    Stone_Spoon ,
    Silver_Spoon ,
    Gold_Spoon ,
    BoxingGlove ,
    FishingRod ,
    Scissors ,
    Slingshot ,
    Branch ,
    Ground,
    Torch ,
    GoldOre,
    Hairball,
    Ice ,
    IronOre ,
    SilverOre,
    Snow ,
    Stone ,
    Wood ,
    Bread ,
    Bread_white ,
    Fish_blue ,
    Fish_blue_grilled ,
    Fish_red ,
    Fish_red_grilled ,
    Flour ,
    Icecream ,
    Meat_monster ,
    Meat_monster_meatball ,
    Meat_monster_skewers ,
    Popcorn ,
    Salt ,
    Sugar ,
    Tanghulu ,
    Tanghulu_ice ,
    Water ,
    Wheat ,
    Crafting_Table ,
    House_Duck_Tent ,
    House_Ggong_Ggong ,
    House_Igloo ,
    House_One_Btn_Tent ,
    Cooking_Bonfire ,
    Cooking_Pot ,
    WaterMelon ,
    WaterMelonSeed ,
    StrawBerry ,
    StrawBerrySeed ,
    Carrot ,
    CarrotSeed ,
    PineApple ,
    PineAppleSeed ,
}
